services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: iastech-app

    volumes:
      - ./app:/app/app
      - ./data:/app/data
      - ./dataset:/app/dataset
      - ./tests:/app/tests

    working_dir: /app

    environment:
      PYTHONUNBUFFERED: "1"

    command: python -m app.test_text_regions
