# Configurações MSER

MSER_MIN_WIDTH = 2
MSER_MIN_HEIGHT = 5
MSER_MAX_WIDTH = 60
MSER_MAX_HEIGHT = 60
MSER_MIN_AREA = 20

DARK_PIXEL_THRESHOLD = 100
MIN_DARK_RATIO = 0.08


# Configurações de agrupamento

GROUP_VERTICAL_TOLERANCE = 0.6
GROUP_HORIZONTAL_TOLERANCE = 2.0
MERGE_VERTICAL_TOLERANCE = 0.7
MERGE_HORIZONTAL_TOLERANCE = 1.5


# Configurações OCR

OCR_SCALE = 3
OCR_MARGIN = 10
OCR_LANGUAGE = "eng"
OCR_PSM = 7